
services:
  db:
    image: postgres:15
    container_name: user-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
