
services:
  db:
    image: postgres:15
    container_name: user-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  nats:
    image: nats:2.10-alpine
    container_name: notifly-nats
    restart: unless-stopped
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # HTTP monitoring port
    command: ["--jetstream", "--http_port=8222"]
    volumes:
      - nats_data:/data

volumes:
  postgres_data:
  nats_data:
