// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (*Users, error)
	GetUserById(ctx context.Context, id uuid.UUID) (*Users, error)
	GetUserByIdentifier(ctx context.Context, identifier string) (*Users, error)
}

var _ Querier = (*Queries)(nil)
