// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.1
// source: trigger.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationRequest_NotificationType int32

const (
	NotificationRequest_NOTIFICATION_TYPE_UNSPECIFIED NotificationRequest_NotificationType = 0
	NotificationRequest_EMAIL                         NotificationRequest_NotificationType = 1
	NotificationRequest_SMS                           NotificationRequest_NotificationType = 2
	NotificationRequest_PUSH                          NotificationRequest_NotificationType = 3
)

// Enum value maps for NotificationRequest_NotificationType.
var (
	NotificationRequest_NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "EMAIL",
		2: "SMS",
		3: "PUSH",
	}
	NotificationRequest_NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED": 0,
		"EMAIL":                         1,
		"SMS":                           2,
		"PUSH":                          3,
	}
)

func (x NotificationRequest_NotificationType) Enum() *NotificationRequest_NotificationType {
	p := new(NotificationRequest_NotificationType)
	*p = x
	return p
}

func (x NotificationRequest_NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationRequest_NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_trigger_proto_enumTypes[0].Descriptor()
}

func (NotificationRequest_NotificationType) Type() protoreflect.EnumType {
	return &file_trigger_proto_enumTypes[0]
}

func (x NotificationRequest_NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationRequest_NotificationType.Descriptor instead.
func (NotificationRequest_NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_trigger_proto_rawDescGZIP(), []int{0, 0}
}

type TriggerResponse_Status int32

const (
	TriggerResponse_STATUS_UNSPECIFIED TriggerResponse_Status = 0
	TriggerResponse_SUCCESS            TriggerResponse_Status = 1
	TriggerResponse_FAILURE            TriggerResponse_Status = 2
	TriggerResponse_QUEUED             TriggerResponse_Status = 3
)

// Enum value maps for TriggerResponse_Status.
var (
	TriggerResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "SUCCESS",
		2: "FAILURE",
		3: "QUEUED",
	}
	TriggerResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"SUCCESS":            1,
		"FAILURE":            2,
		"QUEUED":             3,
	}
)

func (x TriggerResponse_Status) Enum() *TriggerResponse_Status {
	p := new(TriggerResponse_Status)
	*p = x
	return p
}

func (x TriggerResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TriggerResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_trigger_proto_enumTypes[1].Descriptor()
}

func (TriggerResponse_Status) Type() protoreflect.EnumType {
	return &file_trigger_proto_enumTypes[1]
}

func (x TriggerResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TriggerResponse_Status.Descriptor instead.
func (TriggerResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_trigger_proto_rawDescGZIP(), []int{1, 0}
}

type NotificationRequest struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Type          NotificationRequest_NotificationType `protobuf:"varint,1,opt,name=type,proto3,enum=common.trigger.NotificationRequest_NotificationType" json:"type,omitempty"`
	Recipient     string                               `protobuf:"bytes,2,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Subject       string                               `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                               `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationRequest) Reset() {
	*x = NotificationRequest{}
	mi := &file_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationRequest) ProtoMessage() {}

func (x *NotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationRequest.ProtoReflect.Descriptor instead.
func (*NotificationRequest) Descriptor() ([]byte, []int) {
	return file_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationRequest) GetType() NotificationRequest_NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationRequest_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *NotificationRequest) GetRecipient() string {
	if x != nil {
		return x.Recipient
	}
	return ""
}

func (x *NotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *NotificationRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type TriggerResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         TriggerResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=common.trigger.TriggerResponse_Status" json:"status,omitempty"`
	Message        string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	NotificationId string                 `protobuf:"bytes,3,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	TriggerBy      string                 `protobuf:"bytes,4,opt,name=trigger_by,json=triggerBy,proto3" json:"trigger_by,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerResponse) GetStatus() TriggerResponse_Status {
	if x != nil {
		return x.Status
	}
	return TriggerResponse_STATUS_UNSPECIFIED
}

func (x *TriggerResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *TriggerResponse) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *TriggerResponse) GetTriggerBy() string {
	if x != nil {
		return x.TriggerBy
	}
	return ""
}

var File_trigger_proto protoreflect.FileDescriptor

const file_trigger_proto_rawDesc = "" +
	"\n" +
	"\rtrigger.proto\x12\x0ecommon.trigger\"\x80\x02\n" +
	"\x13NotificationRequest\x12H\n" +
	"\x04type\x18\x01 \x01(\x0e24.common.trigger.NotificationRequest.NotificationTypeR\x04type\x12\x1c\n" +
	"\trecipient\x18\x02 \x01(\tR\trecipient\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\"S\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05EMAIL\x10\x01\x12\a\n" +
	"\x03SMS\x10\x02\x12\b\n" +
	"\x04PUSH\x10\x03\"\xfb\x01\n" +
	"\x0fTriggerResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\x0e2&.common.trigger.TriggerResponse.StatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x0fnotification_id\x18\x03 \x01(\tR\x0enotificationId\x12\x1d\n" +
	"\n" +
	"trigger_by\x18\x04 \x01(\tR\ttriggerBy\"F\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x02\x12\n" +
	"\n" +
	"\x06QUEUED\x10\x032m\n" +
	"\x0eTriggerService\x12[\n" +
	"\x13TriggerNotification\x12#.common.trigger.NotificationRequest\x1a\x1f.common.trigger.TriggerResponseB0Z.github.com/pixperk/notifly/common/gen;commonpbb\x06proto3"

var (
	file_trigger_proto_rawDescOnce sync.Once
	file_trigger_proto_rawDescData []byte
)

func file_trigger_proto_rawDescGZIP() []byte {
	file_trigger_proto_rawDescOnce.Do(func() {
		file_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trigger_proto_rawDesc), len(file_trigger_proto_rawDesc)))
	})
	return file_trigger_proto_rawDescData
}

var file_trigger_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trigger_proto_goTypes = []any{
	(NotificationRequest_NotificationType)(0), // 0: common.trigger.NotificationRequest.NotificationType
	(TriggerResponse_Status)(0),               // 1: common.trigger.TriggerResponse.Status
	(*NotificationRequest)(nil),               // 2: common.trigger.NotificationRequest
	(*TriggerResponse)(nil),                   // 3: common.trigger.TriggerResponse
}
var file_trigger_proto_depIdxs = []int32{
	0, // 0: common.trigger.NotificationRequest.type:type_name -> common.trigger.NotificationRequest.NotificationType
	1, // 1: common.trigger.TriggerResponse.status:type_name -> common.trigger.TriggerResponse.Status
	2, // 2: common.trigger.TriggerService.TriggerNotification:input_type -> common.trigger.NotificationRequest
	3, // 3: common.trigger.TriggerService.TriggerNotification:output_type -> common.trigger.TriggerResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trigger_proto_init() }
func file_trigger_proto_init() {
	if File_trigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trigger_proto_rawDesc), len(file_trigger_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trigger_proto_goTypes,
		DependencyIndexes: file_trigger_proto_depIdxs,
		EnumInfos:         file_trigger_proto_enumTypes,
		MessageInfos:      file_trigger_proto_msgTypes,
	}.Build()
	File_trigger_proto = out.File
	file_trigger_proto_goTypes = nil
	file_trigger_proto_depIdxs = nil
}
